#!/bin/bash
# Configura o fuso horário para São Paulo
timedatectl set-timezone America/Sao_Paulo
clear

if [[ $(uname -m) == "aarch64" ]]; then
    rm -rf install* > /dev/null 2>&1
    wget raw.githubusercontent.com/nandoslayer/scripts/refs/heads/main/sshplusarm64 > /dev/null 2>&1 && chmod +x sshplusarm64 && ./sshplusarm64
    cat /dev/null > ~/.bash_history && history -c
    rm -rf wget-log* > /dev/null 2>&1
    exit;
else
    rm -rf install* > /dev/null 2>&1
    wget raw.githubusercontent.com/nandoslayer/scripts/refs/heads/main/sshplusinstall > /dev/null 2>&1 && chmod +x sshplusinstall && ./sshplusinstall
    cat /dev/null > ~/.bash_history && history -c
    rm -rf wget-log* > /dev/null 2>&1
    exit;
fi
